# Numpy
Función: Es trabajar con vectores y matrices de forma rápida

## EDA 
Explorative Data Analysis
1. Obtener datos
2. Manipular y transformar
3. Ver estadísticas, operar datos
4. Visualización de datos

In [27]:
import numpy as np

#### Bases

In [28]:
# dtype= int32, float32 o float 64
# Array unidimensional
array1 = np.array([25,30,35,45,80],dtype='int32')
array1

array([25, 30, 35, 45, 80])

In [29]:
#Matrices
matriz1 = np.array([[52.20,20.0],[30.05,80.69]])
matriz1

array([[52.2 , 20.  ],
       [30.05, 80.69]])

In [30]:
matriz2 = np.array([[52.20,20.0],[30.05,80.69],[90,59]])
matriz2

array([[52.2 , 20.  ],
       [30.05, 80.69],
       [90.  , 59.  ]])

In [31]:
print('La dimension del array 1:',array1.ndim)
print('La dimension del array 2:',matriz1.ndim)
print('La dimension del array 3:',matriz2.ndim)

La dimension del array 1: 1
La dimension del array 2: 2
La dimension del array 3: 2


In [32]:
#shape
print(matriz1.shape)
print(matriz2.shape)

(2, 2)
(3, 2)


In [33]:
#averiguar los tipos de datos
print(array1.dtype)
print(matriz1.dtype)

int32
float64


In [34]:
#tamaño 
print(array1.itemsize)
print(matriz1.itemsize)

4
8


In [35]:
#numero de elementos
print(array1.size)
print(matriz1.size)

5
4


#### Selección y visualización de datos


In [36]:
#acceder aun unico elemento
matriz1[1,1]

80.69

In [37]:
#tomar fila
matriz2[0:1,:]

array([[52.2, 20. ]])

#### Crear o inicializar matrices

In [38]:
# Crear matriz de ceros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.ones((3,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [40]:
np.full((3,3),25,dtype='int32')

array([[25, 25, 25],
       [25, 25, 25],
       [25, 25, 25]])

In [41]:
np.random.rand(2,2)

array([[0.04210803, 0.01527495],
       [0.91982332, 0.44476745]])

In [42]:
np.random.randint(20,30,size=(2,2))

array([[25, 21],
       [29, 29]])

In [43]:
#matri identidad
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

#### Operaciones con escalares

In [44]:
array1

array([25, 30, 35, 45, 80])

In [45]:
array1+2

array([27, 32, 37, 47, 82])

In [46]:
array1-2

array([23, 28, 33, 43, 78])

In [47]:
array1*5

array([125, 150, 175, 225, 400])

In [48]:
array1**5

array([    9765625,    24300000,    52521875,   184528125, -1018167296],
      dtype=int32)

In [49]:
array1/5

array([ 5.,  6.,  7.,  9., 16.])

#### Operaciones entre Matrices

In [50]:
A = np.array([[52.20,20.05],[30.05,80.69],[90.2,59.3]])
B = np.array([[22,20.08],[80.05,10.10],[10.5,29.3]])

In [51]:
A

array([[52.2 , 20.05],
       [30.05, 80.69],
       [90.2 , 59.3 ]])

In [52]:
B

array([[22.  , 20.08],
       [80.05, 10.1 ],
       [10.5 , 29.3 ]])

In [53]:
#sumar dos matrices
np.add(A,B)

array([[ 74.2 ,  40.13],
       [110.1 ,  90.79],
       [100.7 ,  88.6 ]])

In [54]:
np.subtract(A,B)

array([[ 3.020e+01, -3.000e-02],
       [-5.000e+01,  7.059e+01],
       [ 7.970e+01,  3.000e+01]])

In [55]:
#Multiplicacion de elemento a elemento
np.multiply(A,B)

array([[1148.4   ,  402.604 ],
       [2405.5025,  814.969 ],
       [ 947.1   , 1737.49  ]])

In [56]:
#Division de elemento
np.divide(A,B)

array([[2.37272727, 0.99850598],
       [0.37539038, 7.98910891],
       [8.59047619, 2.02389078]])

In [57]:
# Multiplicacion de matrices
A.shape
C=np.array([[52.20,20.05,85.6],[30.05,80.69,859.3]])
AC = np.dot(A,C)

In [58]:
#Trasponer
(AC.T)

array([[ 3327.3425,  3993.3445,  6490.405 ],
       [ 2664.4445,  7113.3786,  6593.427 ],
       [21697.285 , 71909.197 , 58677.61  ]])